sudo: required
language: generic
services:
 - docker

before_install:
  - docker build -t evilfrees/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true evilfrees/docker-react npm run test -- --coverage