version: '3'
services:
  web:
    environment:
     - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
     - "3000:3000"
    volumes:
     - /app/node-modules
     - .:/app
  tests:
    environment:
     - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /app/node-modules
      - .:/app
    command: ["npm","run", "test"]